stages:
  - build
  - test

variables:
  CI_REGISTRY_IMAGE: "tp-gps-11/gps_g11"
  CI_REGISTRY: "registry.gitlab.com"

build-job:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - export DOCKER_TAG=$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID
    - export DOCKER_TAG_LATEST=$CI_COMMIT_REF_SLUG-latest
    - docker build -t $CI_REGISTRY/$CI_REGISTRY_IMAGE:$DOCKER_TAG .
    - docker tag $CI_REGISTRY/$CI_REGISTRY_IMAGE:$DOCKER_TAG $CI_REGISTRY/$CI_REGISTRY_IMAGE:$DOCKER_TAG_LATEST
    - docker push $CI_REGISTRY/$CI_REGISTRY_IMAGE:$DOCKER_TAG
    - docker push $CI_REGISTRY/$CI_REGISTRY_IMAGE:$DOCKER_TAG_LATEST
  only:
    - qa
    - main

unit-test-job:   
  image: maven:3.8.4-openjdk-17-slim 
  stage: test    
  script: 
    - echo "Running unit tests…"
    - mvn test


sonarcloud-job:
  stage: test
  script:
    - echo "Replace with the script provided by sonarcloud"
#stages:
#  - build
#  - test
#
#build:
#  stage: build
#  image: maven:3.8.1-openjdk-17-slim
#  script:
#    - export NEW_VERSION=${CI_COMMIT_SHA:0:8}-${CI_COMMIT_REF_NAME}
#    - mvn versions:set -DnewVersion=1-$NEW_VERSION
#    - mvn -s ci_settings.xml deploy
#  only:
#    - qa
#    - main
#
#unit-test-job:
#  stage: test
#  image: maven:3.8.1-openjdk-17-slim
#  script:
#    - mvn test